#!/bin/bash

WORK_TREE="<work_tree>"
GIT_DIR="<git_dir>.git"
BRANCH="<branch>"

if [ ! -d "$WORK_TREE" ]; then
  echo "WORK_TREE folder does not exist. We cannot deploy!"
  exit 1
fi

while read oldrev newrev ref
do
  if [ "$ref" = "refs/heads/$BRANCH" ];
  then
    echo "Ref $ref received. Deploying ${BRANCH} branch to staging..."
    git --work-tree=$WORK_TREE --git-dir=$GIT_DIR checkout -f $BRANCH
  else
    echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
  fi
done

# # symlink public folder
# echo "Symlink public folder..."
# ln -s $WORK_TREE/web $WORK_TREE/public

# # install vendors
# echo "Install Composer"
# cd $WORK_TREE && composer install

echo "Run post deployment script"
## extra
## eof_extra