#!/bin/bash

WORK_TREE="/srv/users/<whoami>/apps/<repository>"
GIT_DIR="/srv/users/<whoami>/apps/repositories/<repository>.git"
BRANCH="<branch>"

while read oldrev newrev ref
do
  if [ "$ref" = "refs/heads/$BRANCH" ];
  then
    echo "Ref $ref received. Deploying ${BRANCH} branch to staging..."
    git --work-tree=$WORK_TREE --git-dir=$GIT_DIR checkout -f $BRANCH
  else
    echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
  fi
done

# symlink public folder
echo "Symlink public folder..."
ln -s $WORK_TREE/web $WORK_TREE/public

# install vendors
echo "Install Composer"
cd $WORK_TREE && composer install
